<?php
/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>

<?php $layout = $block->getLayout(); ?>

<div class="product info detailed" id="accordion" data-mage-init='{
    "accordion":{
    "active": [0],
    "collapsible": true,
    "openedState": "active",
    "multipleCollapsible": false
    }}'>

    <?php foreach ($detailedInfoGroup as $name) :?>
    <?php $html = $layout->renderElement($name);
        if (!trim($html)) {
        continue;
        }
        $alias = $layout->getElementAlias($name);
        $label = $block->getChildData($alias, 'title');
    ?>

    <hr>
        <div class="data item title" data-role="collapsible">
            <div data-role="trigger">
                <a><?= /* @noEscape */ $label ?></a>
            </div>
        </div>
        <div class="product info detailed content" data-role="content"><?= /* @noEscape */ $html ?></div>

    <?php endforeach;?>

</div>

<?php endif; ?>

<hr>
