<div class="extra-content-main-header-text">Why We Love It</div>
    <div class="extra-content-container">
        <div class="extra-content-flex-child">
            <div class="extra-content-small-container"><img class="extra-content-main-image" src="<?= $block->getViewFileUrl("images/love/1.jpg"); ?>" alt="Classic Crew Neck Aran Sweater">
                <div class="extra-content-heading">Classic Crew Neck</div>
                <div class="extra-content-hr-line-green"></div>
                <div class="extra-content-text-blurb-height">
                    <div class="extra-content-text-blurb">A must have wardrobe staple that never dates.</div>
                </div>
            </div>
        </div>
        <div class="extra-content-flex-child">
            <div class="extra-content-small-container"><img class="extra-content-main-image" src="<?= $block->getViewFileUrl("images/love/2.jpg"); ?>" alt="Exquisitely Crafted Aran Stitches Sweater">
                <div class="extra-content-heading">Exquisitely Crafted Aran Stitches</div>
                <div class="extra-content-hr-line-green"></div>
                <div class="extra-content-text-blurb-height">
                    <div class="extra-content-text-blurb">The classic Honeycomb stitch takes center stage. A tribute to the honeybee and believed to bring the wearer good fortune.</div>
                </div>
            </div>
        </div>
        <div class="extra-content-flex-child">
            <div class="extra-content-small-container"><img class="extra-content-main-image" src="<?= $block->getViewFileUrl("images/love/3.jpg"); ?>" alt="traditional handknitted soft merino Aran Sweater">
                <div class="extra-content-heading">Beautifully Soft Merino Yarn</div>
                <div class="extra-content-hr-line-green"></div>
                <div class="extra-content-text-blurb-height">
                    <div class="extra-content-text-blurb">Beautifully crafted from easy to wear merino wool in a range of irresistible colors.</div>
                </div>
            </div>
        </div>
    </div>
