<a href="#" class="size-modal">
    <i>Size chart</i>
</a>

<div class="size_modal">
    <div class="pschart-popup">
        <div class="pschart-popup-internal">
            <div class="pschart-content">
                <div class="window-title">
                    <h3>Traditional Ladies Aran Sweater - Size Chart</h3>
                </div>
                    <div id="tab_element">
                        <ul class="size-guide-chart-metric-switch">
                            <li class="in_active"><a href="#tab1_content"><span>Inches</span></a></li>
                            <li class="cm"><a href="#tab2_content"><span>Centimeters</span></a></li>
                        </ul>
                    </div>
                    <div id="tab_element_content">
                        <table id="tab1_content" class="table_size cm">
                            <tbody>
                            <tr><th><strong>Our Sizing</strong></th><th><strong>S</strong></th><th><strong>M</strong></th><th><strong>L</strong></th><th><strong>XL</strong></th><th><strong>XXL</strong></th></tr>
                            <tr>
                                <td><strong>Chest</strong></td>
                                <td>50</td>
                                <td>52</td>
                                <td>54</td>
                                <td>56</td>
                                <td>58</td>
                            </tr>
                            <tr>
                                <td><strong>Waist</strong></td>
                                <td>42</td>
                                <td>44</td>
                                <td>46</td>
                                <td>48</td>
                                <td>50</td>
                            </tr>
                            <tr>
                                <td><strong>Length</strong></td>
                                <td>83</td>
                                <td>84</td>
                                <td>85</td>
                                <td>86</td>
                                <td>87</td>
                            </tr>
                            <tr>
                                <td><strong>Arm Length</strong></td>
                                <td>57</td>
                                <td>58</td>
                                <td>59</td>
                                <td>60</td>
                                <td>61</td>
                            </tr>
                            </tbody>
                        </table>
                        <table id="tab2_content" class="table_size in active">
                            <tbody>
                            <tr><th><strong>Our Sizing</strong></th><th><strong>S</strong></th><th><strong>M</strong></th><th><strong>L</strong></th><th><strong>XL</strong></th><th><strong>XXL</strong></th></tr>
                            <tr>
                                <td><strong>Chest</strong></td>
                                <td>19.7</td>
                                <td>20.5</td>
                                <td>21.3</td>
                                <td>22</td>
                                <td>22.8</td>
                            </tr>
                            <tr>
                                <td><strong>Waist</strong></td>
                                <td>16.5</td>
                                <td>17.3</td>
                                <td>18.1</td>
                                <td>18.9</td>
                                <td>19.1</td>
                            </tr>
                            <tr>
                                <td><strong>Length</strong></td>
                                <td>32.7</td>
                                <td>33.1</td>
                                <td>33.5</td>
                                <td>33.9</td>
                                <td>34.3</td>
                            </tr>
                            <tr>
                                <td><strong>Arm Length</strong></td>
                                <td>22.4</td>
                                <td>22.8</td>
                                <td>23.2</td>
                                <td>23.6</td>
                                <td>24</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                <div class="window-title">
                    <h4>Helpful Tips</h4>
                </div>
                <p>Being a natural&nbsp;fibre, wool has a certain amount of flexibility and size may vary slightly.&nbsp;Our chest width measurements are calculated by measuring across the fullest part of the chest.</p>
                <div class="how-to-measure-container">
                    <div class="how-to-measure-image"><img class="sizes" src="https://www.theirishstore.com/media/wysiwyg/Size_Guide_Images/cardonl07.jpg" alt="Measurements" width="420" height="421"></div>
                    <div class="how-to-measure-content">
                        <div class="window-title">
                            <h4>How To Measure</h4>
                        </div>
                        <div style="display: block;">
                            <p class="measure-heading"><strong>CHEST</strong>:</p>
                            <p class="measure-text">Measure across the fullest part of your chest.</p>
                        </div>
                        <div style="display: block;">
                            <p class="measure-heading"><strong>WAIST</strong>:</p>
                            <p class="measure-text">Bend to one side to find the natural crease of your waist; measure across this point.</p>
                        </div>
                        <div style="display: none;">
                            <p class="measure-heading"><strong>HIPS</strong>:</p>
                            <p class="measure-text">Standing with your feet together, measure around the fullest part.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
    ".size-modal": {
        "sizeModal": {}
    }
}
</script>
