<!--<div id="accordion" data-mage-init='{
        "accordion":{
            "active": [1, 2],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Title 1</h4>
        </div>
    </div>
    <div data-role="content">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Title 2</h4>
        </div>
    </div>
    <div data-role="content"> It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h4>Title 3</h4>
        </div>
    </div>
    <div data-role="content">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</div>
</div>-->


<!--<button type="button" class="action" data-trigger="trigger">
    <span>Click</span>
</button>
<div data-mage-init='{"Magento_Ui/js/modal/modal":{
            "type": "popup",
            "title": "Popup title",
            "trigger": "[data-trigger=trigger]",
            "responsive": true,
            "buttons": [{
                "text": "Submit",
                "class": "action"
            }]
        }}'>
    <div class="content">
        Popup Content
    </div>
</div>-->

<!--<script>
    require([
        'jquery',
        'accordion'], function ($) {
        $("#element").accordion();
    });
</script>-->

<div class="content">
    Hello World!
</div>

<p class="click">Click</p>

<script type="text/x-magento-init">
{
    ".click": {
        "Magento_Theme/js/test2": {"config": {"modalClass": ".test_modal"}}
    }
}
</script>
