<!--<div class="wrapper">
    <ul class="test">
        <li class="item">1</li>
        <li class="item">2</li>
        <li class="item">3</li>
        <li class="item">4</li>
        <li class="item">5</li>
    </ul>
</div>-->

<div class="slider-title"><h4><span>Our Top Picks</span></h4></div>
<div class="slider">
    <div class="slider-wrapper">
        <a class="slider-control slider-control-left" href="#" role="button"></a>
        <a class="slider-control slider-control-right slider-control-show" href="#" role="button"></a>
        <div class="slider-item">
            <div class="slider-item-images">
                <img class="image-photo" src="<?= $block->getViewFileUrl("images/slider/wknit137-m-wknit135-p-hd4025.jpg"); ?>" alt="Hooded Aran Zipper Coat Charcoal">
            </div>
            <div class="slider-item-content">
                <a class="slider-item-title" href="#">Hooded Aran Zipper Coat</a>
                <div class="slider-item-price">
                    <div class="slider-item-price-was">Was <span>$149.95</span></div>
                    <div class="slider-item-price-now">Now <span>$99.95</span></div>
                </div>
            </div>
        </div>
        <div class="slider-item">
            <div class="slider-item-images">
                <img class="image-photo" src="<?= $block->getViewFileUrl("images/slider/solvp93-s46615-_2__3.jpg"); ?>" alt="Connemara Marble Disc Earrings & Pendant Jewelry Set">
            </div>
            <div class="slider-item-content">
                <a class="slider-item-title" href="#">Connemara Marble Disc Earrings & Pendant Jewelry Set</a>
                <div class="slider-item-price">
                    <div class="slider-item-price-was">$72.76</div>
                    <div class="slider-item-price-now">Now <span>$70.00</span></div>
                </div>
            </div>
        </div>
        <div class="slider-item">
            <div class="slider-item-images">
                <img class="image-photo" src="<?= $block->getViewFileUrl("images/slider/dress.png"); ?>" alt="Cape Clear Charcoal Aran Dress">
            </div>
            <div class="slider-item-content">
                <a class="slider-item-title" href="#">The Cape Clear Aran Dress - NEW</a>
                <div class="slider-item-price">
                    <div class="slider-item-price-was">Was <span>$100.07</span></div>
                    <div class="slider-item-price-now">Now <span>$90.97</span></div>
                </div>
            </div>
        </div>
        <div class="slider-item">
            <div class="slider-item-images">
                <img class="image-photo" src="<?= $block->getViewFileUrl("images/slider/oknit55-l-oknit55-p-ad22.jpg"); ?>" width="207" height="207" alt="Charcoal Lough Dan Aran Cardigan">
            </div>
            <div class="slider-item-content">
                <a class="slider-item-title" href="#">The Lough Dan Aran Cardigan - NEW</a>
                <div class="slider-item-price">
                    <div class="slider-item-price-was">Was <span>$109.17</span></div>
                    <div class="slider-item-price-now">Now <span>$90.97</span></div>
                </div>
            </div>
        </div>
        <div class="slider-item">
            <div class="slider-item-images">
                <img class="image-photo" src="<?= $block->getViewFileUrl("images/slider/oknit24_e17-24_oknit24-p_cream_2_.jpg"); ?>" width="207" height="207" alt="The Valentia Aran Cardigan">
            </div>
            <div class="slider-item-content">
                <a class="slider-item-title" href="#">The Valentia Aran Cardigan</a>
                <div class="slider-item-price">
                    <div class="slider-item-price-was">Was <span>$118.27</span></div>
                    <div class="slider-item-price-now">Now <span>$90.97</span></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".slider": {
            "testjs": {}
        }
    }
</script>
